### ISSUE TITLE
404, Not Found

### ISSUE THREAD

**Issue by dave-4k** [dialtoneuk/Syscrack#5]
Got so many "404" Not Found.
You've hit rock bottom my friend, scoot on back to the index.

`/game/computers` redirect to `/framework/error/notfound/`
`/game/accountbook` redirect to `/framework/error/notfound/`
`/admin/computer/1` redirect to `/framework/error/notfound/`

**Comment by dialtoneuk** [comment]
This has been fixed in the most recent patch. Please check out the
